# fly.toml app configuration file generated for stockflows on 2026-06-24T08:11:26-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stockflows'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  LOG_LEVEL = 'info'
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '120s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
