name = "StockFlows"
client_id = "9563680320c6d9dd9fbf24b206166eec"
application_url = "https://stockflows.app"
embedded = true
handle = "stockflows-app"

[access_scopes]
scopes = """
  read_inventory,
  write_inventory,
  read_products,
  write_products,
  read_locations,
  write_content,
  read_orders
"""
optional_scopes = [
  "read_product_listings",
  "read_shipping"
]
use_legacy_install_flow = false

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[auth]
redirect_urls = [
  "https://stockflows.app/auth/callback",
  "https://stockflows.app/auth/shopify/callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [
  "inventory_levels/update",
  "inventory_levels/connect",
  "inventory_levels/disconnect",
  "inventory_items/create",
  "inventory_items/update",
  "inventory_items/delete",
  "variants/in_stock",
  "variants/out_of_stock",
  "locations/create",
  "locations/update",
  "locations/delete",
  "products/create",
  "products/update",
  "orders/create",
  "orders/updated",
  "app/uninstalled"
]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact",
]
uri = "https://stockflows.app/webhooks"

[app_proxy]
url = "https://stockflows.app/proxy"
subpath = "stockflows"
prefix = "apps"

[pos]
embedded = true

[app_preferences]
url = "https://stockflows.app/app/settings"

[build]
automatically_update_urls_on_dev = false
