/**
 * Auto-reorder — generates draft purchase orders from reorder alerts.
 *
 * Groups pending alerts by vendor (via the item's most-used vendor from
 * historical POs) and creates one draft PO per vendor with the recommended
 * quantities.
 */

import { prisma } from "~/lib/db/client";
import { logger } from "~/lib/logger";
import { createPO } from "./service";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface AutoReorderResult {
  poId: string;
  poNumber: string;
  vendorName: string;
  lineItemCount: number;
  totalUnits: number;
}

// ---------------------------------------------------------------------------
// Auto-reorder logic
// ---------------------------------------------------------------------------

/**
 * Generate draft purchase orders from pending reorder alerts.
 *
 * For each alert:
 *   1. Find the vendor most frequently used for that inventory item's past POs
 *   2. Group alerts by vendor
 *   3. Create one draft PO per vendor with the recommended order quantities
 *
 * Alerts that already have a linked PO are skipped.
 *
 * @param shopId - Shop to generate POs for
 * @param createdBy - User ID of the person triggering auto-reorder
 * @returns Array of created POs
 */
export async function generateAutoReorderPOs(
  shopId: string,
  createdBy: string,
): Promise<AutoReorderResult[]> {
  logger.info({ shopId }, "generateAutoReorderPOs: starting");

  // Fetch pending alerts with inventory item and location data
  const alerts = await prisma.reorderAlert.findMany({
    where: {
      shopId,
      status: "PENDING",
    },
    include: {
      inventoryItem: true,
      location: true,
    },
  });

  if (alerts.length === 0) {
    logger.info({ shopId }, "No pending alerts — skipping auto-reorder");
    return [];
  }

  // Get the shop's default location for new POs
  const shop = await prisma.shop.findUnique({ where: { id: shopId } });
  if (!shop) throw new Error(`Shop ${shopId} not found`);

  // Find the vendor for each alert by checking historical POs
  const vendorGroups = new Map<
    string,
    {
      vendorId: string;
      vendorName: string;
      locationId: string;
      items: Array<{
        inventoryItemId: string;
        title: string;
        sku: string | null;
        recommendedQty: number;
        costPerUnit: number | null;
      }>;
    }
  >();

  for (const alert of alerts) {
    const item = alert.inventoryItem;
    const locationId = alert.locationId;

    // Find the most-used vendor for this item
    const vendorResult = await prisma.pOLineItem.groupBy({
      by: ["poId"],
      where: {
        inventoryItemId: item.id,
      },
      _count: true,
      orderBy: { _count: { poId: "desc" } },
      take: 1,
    });

    let vendorId = "";
    let vendorName = "Unknown Vendor";

    if (vendorResult.length > 0) {
      const po = await prisma.purchaseOrder.findUnique({
        where: { id: vendorResult[0].poId },
        select: { vendorId: true },
      });
      if (po) {
        vendorId = po.vendorId;
        const vendor = await prisma.vendor.findUnique({
          where: { id: vendorId },
          select: { name: true },
        });
        if (vendor) vendorName = vendor.name;
      }
    }

    // If no vendor found, use a fallback group
    const groupKey = vendorId || `_no_vendor_${locationId}`;
    if (!vendorGroups.has(groupKey)) {
      vendorGroups.set(groupKey, {
        vendorId,
        vendorName,
        locationId,
        items: [],
      });
    }

    const group = vendorGroups.get(groupKey)!;
    group.items.push({
      inventoryItemId: item.id,
      title: item.title,
      sku: item.sku,
      recommendedQty: alert.recommendedQty,
      costPerUnit: item.costPerUnit,
    });
  }

  // Create POs
  const results: AutoReorderResult[] = [];

  for (const [_key, group] of vendorGroups) {
    if (!group.vendorId) {
      logger.warn(
        { shopId, itemCount: group.items.length },
        "Skipping items with no vendor — cannot create PO without a vendor",
      );
      continue;
    }

    // Generate PO number
    const poCount = await prisma.purchaseOrder.count({ where: { shopId } });
    const poNumber = `AUTO-${String(poCount + 1).padStart(4, "0")}`;

    try {
      const po = await createPO({
        shopId,
        vendorId: group.vendorId,
        locationId: group.locationId,
        poNumber,
        lineItems: group.items.map((item) => ({
          inventoryItemId: item.inventoryItemId,
          quantity: item.recommendedQty,
          unitCost: item.costPerUnit ? Number(item.costPerUnit) : 0,
          notes: "Auto-generated from reorder alert",
        })),
        notes: "Auto-generated by StockFlows reorder system",
        createdBy,
      });

      if (po) {
        results.push({
          poId: po.id,
          poNumber: po.poNumber,
          vendorName: group.vendorName,
          lineItemCount: group.items.length,
          totalUnits: group.items.reduce((sum, i) => sum + i.recommendedQty, 0),
        });

        // Acknowledge the alerts for items included in this PO
        for (const item of group.items) {
          await prisma.reorderAlert.updateMany({
            where: {
              inventoryItemId: item.inventoryItemId,
              locationId: group.locationId,
              status: "PENDING",
            },
            data: {
              status: "ACKNOWLEDGED",
              actedAt: new Date(),
            },
          });
        }

        logger.info(
          {
            poId: po.id,
            poNumber,
            vendorName: group.vendorName,
            itemCount: group.items.length,
          },
          "Auto-reorder PO created",
        );
      }
    } catch (error) {
      logger.error(
        { err: error, vendorName: group.vendorName },
        "Failed to create auto-reorder PO",
      );
    }
  }

  logger.info(
    { shopId, poCount: results.length },
    "generateAutoReorderPOs: done",
  );
  return results;
}
